travis:
  secure:
    BINSTAR_TOKEN: pl2qIfOUriUZofKENAtQQH3W9z43hLAWV1PaTVW6fuCh4b0df8zwc6p/16oGPG7oL/w/DniIYStXWAMvvuw7DsGGNN7aNLiHX9d5WsIHKXYSTG6II6UjAmmOYBZBPhp4y1OV3pWyYXcL3Wp4FvY7gwla1u3/B00uS37k8UKaTti3OIt6VF7J91Wfi8n+QoWcxEApFg83YZF82cnIgVXS1ymzWtO8AcyoBc65M6ZtfA+JKYFBG0uypo86vnI17HHWOwv+m+J8opnAmYxSf/5JIe23LfkHRMxZYYvjMQLUoX+xiJ6Eu4xAyPrzLb0LSWZTuAR5QJfiAcSWxkvQ4OnLqZntRHKhYgLDVjH4b49INo7nI6MreuYhhA5i1bn7yczrlm7jHGFDeasVfTOeeuFcSziHetheot3Q17fV0MY8vdtBD44AriY64jHSLETGZJqrpN+0WEVBdBZVgge5GuUus0miTTQ+PkJQ3grI6rDSO0sUVTk5KWrsJ2+/m+aA5M00UAPWgroBNwGjE0abM7RSjAhtBVwyhHe1r32qx4leCx1j0roQEufjI7cWfgX2BowcBaBhNpgB/gSKDAjCbr3sHLJcdoLASbB5meK1pQ1QLuIBdIfYAhHRMpOF68Q7Zr59U23eO1NNmHdlG45LNIqJGkE/iLcYAEbkSb0qkduYsY8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
